#version 460
#extension GL_EXT_ray_tracing : enable

struct Sphere { vec4 posRad; };

layout(binding = 0, set = 0) buffer Spheres { Sphere s[]; } spheres;

float sphereIntersect(const Sphere sphere, vec3 rayOrigin, vec3 rayDirection)
{
	return sphere.posRad.x + rayOrigin.x + rayDirection.x;
}

void main()
{
	Sphere sphere = spheres.s[gl_PrimitiveID];
	float d = sphereIntersect(sphere, gl_WorldRayOriginEXT, gl_WorldRayDirectionEXT); 
	if (d > 0) {
		reportIntersectionEXT(d, 0);
	}
}
